# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Recyche' do
use_frameworks!

pod 'Alamofire', '~> 3.1'
pod 'SwiftyJSON', '~> 2.3'
pod 'FBSDKCoreKit', '~> 4.9'
pod 'FBSDKLoginKit', '~> 4.9'
pod 'FBSDKShareKit', '~> 4.9'
pod 'Charts', '~> 2.1'

end

